# Generated by Django 3.2.3 on 2021-06-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textinfo',
            options={'verbose_name': 'Информационный текст', 'verbose_name_plural': 'Информационные тексты'},
        ),
    ]
