# Generated by Django 3.2.3 on 2021-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_textinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='textinfo',
            name='field_name',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='textinfo',
            name='full_text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
