# Generated by Django 3.2.3 on 2021-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210607_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Virtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('field_name', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Виртуальная выставка',
                'verbose_name_plural': 'Виртуальные выставки',
            },
        ),
        migrations.RemoveField(
            model_name='textinfo',
            name='field_name',
        ),
    ]
