# Generated by Django 3.2.3 on 2021-06-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_virtual_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='virtual',
            unique_together=set(),
        ),
    ]
