# Generated by Django 3.2.3 on 2021-06-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_virtual_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='virtual',
            unique_together=set(),
        ),
    ]
