# Generated by Django 3.2.3 on 2021-06-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_virtual_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Virtual',
        ),
    ]
