# Generated by Django 3.2.3 on 2021-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_virtual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('title2', models.CharField(max_length=50, verbose_name='Название')),
                ('text2', models.TextField(verbose_name='Текст2')),
                ('title3', models.CharField(max_length=50, verbose_name='Название')),
                ('text3', models.TextField(verbose_name='Текст3')),
            ],
            options={
                'verbose_name': 'Контент для художников',
                'verbose_name_plural': 'Контент для художников',
            },
        ),
        migrations.DeleteModel(
            name='TextInfo',
        ),
    ]
