# Generated by Django 3.2.3 on 2021-06-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210620_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistinfo',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='artistinfo',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='artistinfo',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='artistinfo',
            name='title3',
        ),
    ]
