# Generated by Django 3.2.3 on 2021-06-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210620_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistInfo',
            new_name='ArtistModel',
        ),
    ]
