# Generated by Django 3.2.3 on 2021-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_partnersmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersmodel',
            name='img',
            field=models.ImageField(upload_to='partners', verbose_name='Логотип'),
        ),
    ]
