# Generated by Django 3.2.3 on 2021-06-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_partnersmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersmodel',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
