# Generated by Django 3.2.3 on 2021-06-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_partnersmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersmodel',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
