# Generated by Django 3.2.3 on 2021-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_partnersmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnersmodel',
            name='img',
            field=models.ImageField(upload_to='media/img', verbose_name='Логотип'),
        ),
    ]
