# Generated by Django 3.2.3 on 2021-06-25 16:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_partnersmodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersmodel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='partnersmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='partnersmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
