# Generated by Django 3.2.3 on 2021-07-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_aboutmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='text_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='text_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Текст'),
        ),
    ]
