# Generated by Django 3.2.3 on 2021-07-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210709_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewermodel',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='viewermodel',
            name='lon',
        ),
    ]
