# Generated by Django 3.2.3 on 2021-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210709_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewermodel',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='viewermodel',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
