# Generated by Django 3.2.3 on 2021-09-17 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserModel',
        ),
    ]
