# Generated by Django 3.2.3 on 2021-09-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_userprofile_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
