# Generated by Django 3.2.3 on 2021-09-25 18:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210918_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=users.models.path_avatar),
        ),
    ]
