# Generated by Django 3.2.3 on 2021-06-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Virtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('field_name', models.URLField(blank=True, verbose_name='URL')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Виртуальная выставка',
                'verbose_name_plural': 'Виртуальные выставки',
                'ordering': ['title'],
            },
        ),
    ]
