# Generated by Django 3.2.3 on 2021-06-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtual',
            old_name='field_name',
            new_name='field_name_nolog',
        ),
        migrations.AddField(
            model_name='virtual',
            name='field_name_log',
            field=models.URLField(blank=True, verbose_name='URL2'),
        ),
    ]
