# Generated by Django 3.2.3 on 2021-06-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0002_auto_20210622_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual',
            name='field_name_log',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='virtual',
            name='field_name_nolog',
            field=models.URLField(blank=True, verbose_name='URL2'),
        ),
    ]
