# Generated by Django 3.2.3 on 2021-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0003_auto_20210622_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual',
            name='field_name_log',
            field=models.URLField(blank=True, verbose_name='URL log'),
        ),
        migrations.AlterField(
            model_name='virtual',
            name='field_name_nolog',
            field=models.URLField(blank=True, verbose_name='URL nolog'),
        ),
    ]
